### PR TITLE
Add Filters for collector

### PR DESCRIPTION
**Pull request by ko-be**
Adding filters for Sumo Collector.

### CODE REVIEW

**Comment by ko-be** [comment]
Got the Mask filter to somewhat work.... but seems Mask filter has a line length limit.

It's chopping super long log lines into multiple lines, and the line continues to another sumo log line, and because the line is chopped off mid-regex, the regex doesn't match on the chopped off EnvironmentVariable.

**Comment by bossjones** [comment]
👍

**Comment by digitalyuki** [comment]
@ko-be 
Can you explain how the docker-sources/ directory work?

That will probably explain also why there separate DockerFiles and two parameterized-collector files.

**Comment by ko-be** [comment]
Each Dockerfile produces a different sumologic container, with differing /etc/sumo-sources.json files.

1) Dockerfile in the base dir is for ingesting via local JSON logs
2) syslog dir contains the Dockerfile config for ingesting via ncat of journald logs (journald logs == syslog logs)
3) docker-sources contains the config for ingesting via DockerLog Source and DockerStats Source - this one will require additional changes on the infrastructure side to implement correctly, so currently not used, but left here for future use.

This page describes the various source types:  https://help.sumologic.com/Send_Data/Sources/Use_JSON_to_Configure_Sources

**Pull request merged**
